name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: wglabz/wealthfam-webapp:latest
          build-args: |
            VITE_API_URL=/api/v1
            VITE_PARSER_API_URL=/parser
